### ISSUE TITLE
Python int args converted to Java boolean if method has int and boolean overloads

### ISSUE THREAD

**Issue by userzimmermann** [mrj0/jep#11]
When a Java method is overloaded for `int` and `boolean` args and called with a Python `int`, the `boolean` variant is used:

    >>> System.out.println(2)
    true

For `long` values it works as expected:

    >>> System.out.println(2L)
    2

**Comment by ndjensen** [comment]
I traced this util.c's pyarg_matches_jtype().  Trying to pick the right overloaded method is tricky, it is getting the method that takes a boolean first, and when comparing the arg types does PyInt_Check(param).  Since PyBool extends PyInt, it returns true.  I will switch it to PyBool_Check() on a branch for inclusion in an upcoming release, but this will break anyone who calls a Java method that takes a boolean parameter and was passing along a python integer.

**Comment by ndjensen** [comment]
Ok, that simple fix breaks too much backwards compatibility so I need to back it out for the next release.  I'll need to come up with a more complex fix to do it right so it picks the right method without breaking backwards compatibility.

**Comment by ndjensen** [comment]
This is related to #25.

**Comment by ndjensen** [comment]
Ben's fix is on dev_3.6 branch.

**Comment by ndjensen** [comment]
@bsteffensmeier, is this one also fixed by the fix on #42?  Can you also add a comment to #25 of what was fixed on #42 and what remains to be fixed?

**Comment by bsteffensmeier** [comment]
This should be fixed by the same commit as #42 on 3.6. Specifically all primitives are properly prioritized so an python boolean will be passed to a method with a boolean arg if it exists and a method with an int arg only if there is no method that takes a boolean.
