### ISSUE TITLE
Windows build doesn't work with Microsoft Visual C++ Compiler for Python

### ISSUE THREAD

**Issue by ndjensen** [mrj0/jep#13]
Using setup.py to build the Windows DLL currently relies on Microsoft Visual Studio being installed to make use of the msvc compiler.  However, there also exists another compiler that in theory should work, the Microsoft Visual C++ Compiler for Python.  https://www.microsoft.com/en-us/download/details.aspx?id=44266

Trying to build with that fails with a message such as:
> error: Unable to find vcvarsall.bat

@davelovely investigated and reported the following:
That appears to be this python issue: https://bugs.python.org/issue23246

Looks like there's a few options for a fix:
1. Use Microsoft Visual Studio
2. Add dependency on setuptools and use setuptools
3. Patch our msvccompiler override similar to how setuptools does it: https://bitbucket.org/pypa/setuptools/src/18eceee63709bc70c06b51a609f3dbd2eab07ef4/setuptools/msvc9_support.py?at=default

**Comment by nfalco79** [comment]
After a long long time I build library with success.
With a x86_64 machine is necessary a Visual Studio 2010.

For a different version Visual Studio (Visual Studio 2015 express available on microsoft site) since 2010 you need must define the VS100COMNTOOLS env variable that point to the tool folder of VisualStudio installed (example set VS100COMNTOOLS=%VS140COMNTOOLS%) to miss vcvarsall.bat error. Last Microsoft Visual Studio fails because does not found the manifest file jep.pyd.manifest in build temp directory.

So at the the solution was install a Microsoft Visual C++ for Python 2.7 and setup the variable VS100COMNTOOLS to the C:\Users\%USERNAME%\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0

In any case all Visual Studio compiler breaks on util.h line 48
I redefine macro as follow:
> #define PyString_FromFormat(fmt, ...) PyUnicode_FromFormat(fmt, ##__VA_ARGS__)

**Comment by ndjensen** [comment]
Thank you for sharing your insight.

**Comment by ndjensen** [comment]
Ok.  I finally had a chance to work through Windows builds.  What a pain, and I had other people's notes to assist me!  Anyway, I changed util.h as you suggested and also fixed the problem with the manifest file: a39026f5f21c5409808b6c66f21a13d6dc3d4a3a

I also made very specific instructions on the wiki: https://github.com/mrj0/jep/wiki/Windows

I've now successfully built a 64-bit Jep with python 2.7 and MSVC Express 2008, and a 64-bit Jep with python 3.4 and MSVC Express 2010.  I have not tried it with Microsoft Visual C++ for Python 2.7.  Do you think those problems are now resolved?

**Comment by ndjensen** [comment]
Ok I finally got this working by adding more to https://github.com/mrj0/jep/blob/master/commands/msvc9compiler.py

It's _fairly_ reasonable and not a nightmare now, at least for Python 2.7.  I also updated the documentation to take this into account. https://github.com/mrj0/jep/wiki/Windows

Closing as completed, will probably become part of 3.4.1.
