### ISSUE TITLE
Want object return values, not strings

### ISSUE THREAD

**Issue by kovasb** [mrj0/jep#14]
This is a bit of a noob question, but I can't find any examples online for my use case.

How do I get Python objects back into the JVM, so that I can then manipulate them? 

Using jep.Jep as my entry point, I try to .getValue on an object, but I get back a string:
"<module 'sys' (built-in)>"

Which obviously I can't invoke any relevant methods on. 

Related to this, I find eval to be very confusing: it doesn't return the value that is the result. What is the pattern for evaling something, and then getting the result back into the JVM?

Thanks

**Comment by ndjensen** [comment]
Unfortunately at present it's not easy to get python objects into the JVM and their support in the JVM is limited.   For the most part you can only get Java objects, strings, and primitives into the JVM.  We want to make that significantly easier and more useful in the future.

For now, you could use the Proxy object to implement a java interface with python code.  Otherwise, the simpler solution is to convert the python object into a java object before pulling it or sending it into Java.  Jep will automatically try to do this for you if it's a common type, but if it's not supported jep will fallback  to turning the python object into a string.

eval() is just executing the command inside the String.  So instead of doing
```java
jep.eval("4 + 5");
```
you would want to do
```java
jep.eval("x = 4 + 5")
Integer x = (Integer) jep.getValue("x");
```

**Comment by ndjensen** [comment]
Underneath eval() Jep is using [PyRun_String](https://docs.python.org/2/c-api/veryhigh.html#c.PyRun_String) which does return a result, just jep is dropping the result.  It's operating on the assumption that you may be doing a lot of eval(String) calls to invoke methods, manipulate objects inside the interpreter, etc, and wouldn't want the overhead of transforming the resulting object into a Java equivalent.

I don't think we should change the `public boolean eval(String)` method signature since it's quite established and would break a lot of applications, but for the future we should consider adding another eval method that automatically returned the result.

**Comment by ndjensen** [comment]
Just glanced at the source again.  The code behind `Jep.eval(String)` and `Jep.getValue(String)` is almost identical, with the biggest difference being that `getValue(String)` returns the result.  So you could pass the statement to be evaled to `getValue(String)` for this behavior.  The only thing that wouldn't work is the interactive mode of trying to send multiple statements in.

**Comment by ndjensen** [comment]
Updated wikis/docs in many a place, but in particular [What's typical use of Jep code look like?]( https://github.com/mrj0/jep/wiki/FAQ#whats-the-typical-usage-of-jep-code-look-like)
