### ISSUE TITLE
Maven repository update

### ISSUE THREAD

**Issue by behdad84** [mrj0/jep#15]
Hi,

Can you please share the jar file(s) on maven?  I found the following which looks pretty old. Thanks.

http://mvnrepository.com/artifact/jep/jep/2.24

**Comment by ndjensen** [comment]
That's not the same Jep.  That lists org.nfunk.jep as packages and appears to be Java Expression Parser: http://www.cse.msu.edu/SENS/Software/jep-2.23/doc/website/doc/doc_usage.htm

The Java code is currently built with python's setup.py and using javac, javah, jar, etc.  We don't have plans to support building with maven.  It's complicated given that Jep is useless without the compiled library and python, but it's difficult to ship a compiled library since there are so many possible configurations (32-bit vs 64-bit, java version, python version, numpy version...)

**Comment by behdad84** [comment]
Thank you!

**Comment by orius123** [comment]
but can't you upload at least the jep.jar to maven central so it will be easier too consume in java apps?

**Comment by ndjensen** [comment]
It isn't time-effective for us to manage a maven release without switching the build system to maven.  Since much of Jep is not written in Java and is dependent on native code and python code, switching to maven isn't currently a priority.
