### ISSUE TITLE
Multithreaded calls with Jep

### ISSUE THREAD

**Issue by behdad84** [mrj0/jep#30]
Thanks for your continues support. 

In my java application, in the java side, I create a few threads each having a Jep instance running some python code. So my expectation was that I can make python calls in parallel and gain performance through this but looks like python GIL is avoiding that (due to CPython Global Interpreter lock). In your idea is there a way we can get around this by having python multiprocessing (https://docs.python.org/2/library/multiprocessing.html) library?

I wish I had the option to create one instance of Jep per whole JVM (for all threads) and use a thread-pool in my python script to run my application.

**Comment by ndjensen** [comment]
Yeah, the problem is due to the GIL.  If you look at pyembed.c where jep usually enters python, it acquires the GIL and runs the python code and then releases the GIL.  Jep does have optimizations where for example [it releases the GIL whenever it calls a java method from python](https://github.com/mrj0/jep/blob/master/src/jep/pyjmethod.c#L429).  Some CPython extensions such as numpy also try to release the GIL [whenever they're executing C code that does not make use of the CPython API](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_object.c#L1412).

So how much the GIL affects you depends on your use case.  If you're bouncing back and forth between java and python it's not too bad, but if you're running pure python code that takes a while to complete, unfortunately, the GIL's going to be blocking.

Are you still working with ecos and that is what is blocking?  I don't know anything about that project but it appears ecospy is the bridge between python and the ecos C library, and [ecospy does not appear to be releasing the GIL when it calls into C](https://github.com/embotech/ecos-python/blob/master/src/ecosmodule.c#L636).  Since the C ecos library has no concept of python, it shouldn't need the GIL, and therefore ecospy should be allowing threads while it's in C code that is not using CPython.  For example,

```C
/* Solve! */
Py_UNBLOCK_THREADS;
exitcode = ECOS_BB_solve(myecos_bb_work);
mi_iterations =(long) myecos_bb_work->iter;
Py_BLOCK_THREADS;
```

This is based on the assumption that the call to solve() is not dependent on static variables, as unblocking the threads will allow multi-threading and could be catastrophic if two threads are changing the same variables internally.

I would like to improve Jep to get around some of these threading issues, but the problem seems inherent to CPython itself.

**Comment by ndjensen** [comment]
You can use the `multiprocessing` module from within Jep but I'm unsure of the performance implications.  If you use it, the spawned processes will be children and look like the Java process in _top_ but will actually be pure Python processes.  Therefore you would have to avoid using Java classes/code in the code of the children processes and then send the results back to the main process running Jep.

You could also look into using [Cython](http://cython.org/).  One of the reasons Python can sometimes be slow is because it is interpreted so the definition of any given object or method could be altered dynamically.  If you know a method's code will not change, you could theoretically use Cython to speed it up.  Cython even has methods to release and reacquire the GIL.  I have not used Cython, but in theory it is compatible with Jep since it compiles to CPython compatible code.

**Comment by ndjensen** [comment]
I wrote a section in the documentation regarding the GIL: https://github.com/mrj0/jep/wiki/Jep-and-the-GIL

**Comment by behdad84** [comment]
sorry for replying with delay. Yes I used multiprocessing in my python code (called via Jep) and looks to be working fine.

**Comment by lfcnassif** [comment]
First, thank you for this great library!

I am having bottleneck problems with GIL and tested JEP-3.9.1 with multiprocessing module (python 3.8.6) but the slave processes are failing to initialize and printing:
```
Unrecognized option: -c
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.Error: Could not create the Java Virtual Machine.
```
I don't know where this -c option came from. Is something that could be workarounded?

Thanks

**Comment by makihor** [comment]
@lfcnassif could you please provide a code snippet of using the subprocesses with jep ? I am also very curius how to bypass GIL effectivelly. thanks in advance!

**Comment by lfcnassif** [comment]
Hi @makihor, I was not able to make python multiprocessing module work with JEP, so I have to create my own pool of processes manually. I don't have a small sample code snippet, but here is some implemented code in a larger project:
This runs on java process using JEP:
https://github.com/sepinf-inc/IPED/blob/master/iped-app/resources/config/conf/scripts/FaceRecognitionTask.py
This runs on pure python external processes (the heavy CPU job):
https://github.com/sepinf-inc/IPED/blob/master/iped-app/resources/config/conf/scripts/FaceRecognitionProcess.py

**Comment by makihor** [comment]
thank you for the response @lfcnassif ! It was very interesting to see how the subproces module is used in your examples. Will learn from it as I a mainly a java developer)) We actually plan to sclale the calculations in a distrubuted way in containers of kube cluster, each running an isolated python interpreter. And also to benefit from multiprocessing inside each isolated container using the available CPUs. Will see how it would work. Thank you again!

**Comment by lfcnassif** [comment]
I'm also a java dev and started with python recently, so don-t take my python code as gold standard.

Actually first script could be written completely in java without JEP since it just handles external processes using stdin/stdout for IPC.

If JEP could support python multiprocessing module, that would be a great addition.
