### ISSUE TITLE
Convert Java collections to python counterparts?

### ISSUE THREAD

**Issue by soyvv** [mrj0/jep#39]
Recently I have a use case where I need to frequently transfer a java Map (of String and boxed primitive types) from java code to python code through jep.

In python I will get a PyJobject (of Map) which refers to many other PyJobject for Double/Float etc. 

Though I can add a proxy layer in python to do the conversion, it would be nice and potentially much more efficient if jep could have this conversion built in it, e.g: converting Map/List etc to python dict/list and convert Double/Float/Integer as primitives. 

Also, any suggestion regarding this use case to improve performance?
Thanks!

Zhikai

**Comment by ndjensen** [comment]
Are you using Jep 3.4?  In Jep 3.4 if you send a Java Map into Python you should get a PyJmap which implements the Python mapping protocol.  So it's not a Python dictionary, but it appears like one to the interpreter.  See the [3.4 release notes](https://github.com/mrj0/jep/blob/master/release_notes/3.4-notes.rst#added-pyjmap-type).  It also handles Java Lists similarly.  It's faster for Jep to simulate a dictionary or list rather than convert it to the native Python type, but if you absolutely needed an actual Python dictionary or list then yeah, that wouldn't work and you'd need to add a conversion layer.

Regarding the Object versions of Number primitives, that's complicated.  @bsteffensmeier and I have had numerous conversations about it.  There are scenarios where it would be convenient for it auto-convert to a Python primitive, and then there are scenarios where it is more convenient that it remains as a PyJobject.  Generally if you're using the numbers in Python then it's better to auto-convert to Python primitives, but if you're just sending the Java Numbers around between Java objects/Java method calls, then it's a performance hit to keep converting them back and forth between their Python and Java equivalents.

We haven't come up with a solution that handles both scenarios elegantly.  I've thought about writing a PyJNumber that implements the [Python Number Protocol](https://docs.python.org/2/c-api/number.html) and is used when java.lang.Number objects are in the interpreter instead of primitives, which is similar to how Collections, Maps, Lists, etc are handled.  But I'm not sure how useful that would be, if users could get by with the object implementing the Number protocol, or if they actually need a Python primitive.

**Comment by ndjensen** [comment]
Already had support for collections and maps in Jep 3.4.  Added support for numbers in Jep 3.5.  Closing ticket.

**Comment by Symbolk** [comment]
Hi, I am facing the opposite case, I want to convert python primitive data type into java, any idea how to achieve that except for handling one by one?
