### ISSUE TITLE
Issues with bool type given to a java call

### ISSUE THREAD

**Issue by zinaps0** [mrj0/jep#42]
I have a java class ReducedMethodList that has a method add(Object) for instance.
     I use Jep invoke using this an instance of this class.
     In the invoked method, I go thru a list/tuple ; let's say ('a', 'b', True)
     I call the ReducedMethodList .add(x) call for each element of the list.
     Everything is fine for the strings but I got the error **"jep.JepException: <class 'TypeError'>: Expected object parameter at #"**
     When I print x.__class__, I have:
class 'str'
class 'str'
class 'bool'

     In jep_util.c sources, it's as if it was considering by boolean value as a (case JCHAR_ID: )
     I'm still on the version 3.5rc of Jep and I do not use numphy when compiling Jep.

I created the class:
public class ReducedMethodList {
    ArrayList<Object> lst=new ArrayList<Object>(20);
    public void add(Object o) {
        lst.add(o);
    }
    public ReducedMethodList sub() {
        ReducedMethodList sub = new ReducedMethodList();
        lst.add(sub);
        return sub;
    }
}
The only type available for the add() method is Object.

**Comment by ndjensen** [comment]
I think the problem is in [jep_util.c's pyarg_matches_jtype](https://github.com/mrj0/jep/blob/master/src/jep/jep_util.c#L701).  Specifically the case for [JOBJECT_ID](https://github.com/mrj0/jep/blob/master/src/jep/jep_util.c#L765) is checking for a PyJObject or a PyString and anything else it thinks doesn't match, so it's not recognizing that the boolean parameter True can work with that method.  The fix would be to make it smarter so it checks for PyBool and other types such as PyLong and allow it to go through as an Object.

@bsteffensmeier, I initially thought this would be an easy fix, since the method signature takes an Object as a parameter, just try to get the Python object to whatever Java equivalent.  But thinking about it more, I'm wary that this would raise the odds of calling the wrong method as described in #11 and #25.  If there were two or more methods with the same name and same number of args, since it just goes with the first match as described in those tickets, it in theory could find `add(Object)` before `add(boolean)` and therefore call `add(Object)` when really `add(boolean)` would be more correct.  So I'm wondering if we shouldn't fix this until after those other two are fixed?  What do you think?

**Comment by bsteffensmeier** [comment]
The short answer is that we can fix it easily for pyjmethod but not for pyjmultimethod. Which means that overloaded methods will still fail but as long as there is exactly one method with the same name and number of args it would work. Even though it would be a somewhat partial fix I think it would make sense to do that for this ticket and then leave the work for overloaded methods for #11 or #25.

We don't actually use [pyarg_matches_jtype](../blob/master/src/jep/jep_util.c#L701) in [pyjmethod_call](../blob/master/src/jep/pyjmethod.c#L407). It just does few preliminary checks to [make sure the number of args is correct](..blob/master/src/jep/pyjmethod.c#L434) and [make sure that self is a java object](../blob/master/src/jep/pyjmethod.c#L443) then it jumps [straight into the conversion](../blob/master/src/jep/pyjmethod.c#L481) without ever checking the types of the args. The error message comes from the [conversion itself](../blob/master/src/jep/jep_util.c#L1205).

I also checked version 3.4 to make sure I didn't make anything worse in 3.5 and and in the case of only method with the same name we have always [called the method without checking the args](../blob/dev_3.4/src/jep/pyjobject.c#L591).

We can fix this specific problem without fixing method choosing by making the [JOBJECT_ID case of convert_pyarg_jvalue](../blob/master/src/jep/jep_util.c#L1174) smarter. Specifically it looks like we should be using [pyembed_box_py](../blob/master/src/jep/pyembed.c#L1019) because it supports a variety of different types in addition to bools so we can support all the python types that Jep.getValue() supports.

[pyjmultimethod_call](../blob/master/src/jep/pyjmultimethod.c) is responsible for [verifying method compatibility](../blob/master/src/jep/pyjmultimethod.c#L135) which [checks the type of the args](../blob/master/src/jep/pyjmethod.c#L385). We can't fix that unless we make booleans acceptable as Object arguments which would introduce ambiguity when there are multiple compatibile methods and that would be a risky move until we have a better fix for method choosing. So pyjmultimethod probably won't be fixable until #11 or #25.

**Comment by ndjensen** [comment]
Apparently github auto-closes a ticket since @bsteffensmeier's commit message said fixes #42 and I merged that into master.  I was not expecting that....

Anyway, this is fixed in 3.5.1.  We are now using `pyembed_box_py()` to convert the Python object to its equivalent Java object when your Java method signature takes an Object.  That should work safely for the majority of use cases.  One thing to watch out for is if on the Java side you start seeing weird strings that look like Python representations of an Object, then you've probably hit #43.  That is unlikely to occur as long as you are using PyJObjects or the Python standard built-in objects.

Ben also significantly improved the error message when using incorrect arg types when calling a Java method from Python.
