### ISSUE TITLE
Jep does not work with Python 3.3

### ISSUE THREAD

**Issue by giamma** [mrj0/jep#45]
Import of Java packages in the Jep console fails on Python 3.3 with the following error:

`>>> import java`

> Traceback (most recent call last):
>  File "/usr/local/lib/python3.3/site-packages/jep/console.py", line 61, in prompt
> ran =  jep.eval(line)
>
> RuntimeError: jep.JepException: jep.JepException: <class 'ImportError'>: java.lang.ClassNotFoundException: java.__package__

The second time the __import__ statement is issued in the console it works. 
Please see this forum discussion for further details:  https://groups.google.com/d/msg/jep-project/4QYAcAgjfbc/qigzY7eqBQAJ

**Comment by ndjensen** [comment]
This is my bad.  Python 2.6 and 3.3 don't get much testing from me.  I have since set up a virtual machine with Python 3.3 for testing that.  Maybe someone someday will offer to help write more unit tests and/or set us up with continuous integration.  I briefly looked at [TravisCI](https://travis-ci.org/) but didn't understand how to use it given Jep crosses into building Java, C, and Python.

Anyway, I have a virtual machine with Python 3.3 now, repeated the problem as discussed in email thread, have a fix, and will be fixing it in Jep 3.4 and 3.5 soon.

**Comment by ndjensen** [comment]
Fixed in 3.4.4 and 3.5.2.  Merged forward into dev_3.6.
